### ISSUE TITLE
Стайлгайд, состояния

### ISSUE THREAD

**Issue by baileys-li** [htmlacademy-htmlcss/1946373-sedona-33#11]
Не тот фокус у ссылок в навигации
```css
.navigation-link:focus {
  visibility: hidden;
}
```
![image](https://user-images.githubusercontent.com/47776594/159213883-14209a02-2a73-438d-994f-af27417b561a.png)
